import '../models/sketchy_video.dart';

final List<SketchyVideo> sketchyMicroSeed = [
  // BACTERIA — Gram-Positive Cocci
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Cocci', title: 'Staphylococcus aureus', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Cocci', title: 'Staphylococcus epidermidis & saprophyticus', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Cocci', title: 'Streptococcus pyogenes – Group A Strep', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Cocci', title: 'Streptococcus agalactiae – Group B Strep', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Cocci', title: 'Streptococcus pneumoniae & viridans', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Cocci', title: 'Enterococcus faecium & faecalis', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Cocci', title: 'Streptococcus gallolyticus – Group D Strep', watched: false),
  // Gram-Positive Bacilli
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Bacilli', title: 'Bacillus anthracis & cereus', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Bacilli', title: 'Clostridium tetani', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Bacilli', title: 'Clostridium botulinum', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Bacilli', title: 'Clostridium perfringens', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Bacilli', title: 'Clostridioides difficile', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Bacilli', title: 'Corynebacterium diphtheriae', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Bacilli', title: 'Listeria monocytogenes', watched: false),
  // Gram-Positive Branching
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Branching Filamentous Rods', title: 'Actinomyces israelii', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Positive Branching Filamentous Rods', title: 'Nocardia asteroides', watched: false),
  // Gram-Negative Cocci
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Cocci', title: 'Neisseria Overview', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Cocci', title: 'Neisseria meningitidis', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Cocci', title: 'Neisseria gonorrhoeae', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Cocci', title: 'Moraxella catarrhalis', watched: false),
  // GN Bacilli Enteric
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Klebsiella pneumoniae, Enterobacter spp., Serratia marcescens', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Salmonella: Intro to Salmonella & NTS', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Salmonella: Typhoidal Salmonella', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Shigella spp.', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Escherichia coli – ETC & EHEC', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Yersinia enterocolitica & pestis', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Campylobacter jejuni', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Vibrio spp.', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Helicobacter pylori', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Enteric Tract', title: 'Proteus mirabilis', watched: false),
  // GN Bacilli Respiratory
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Respiratory Tract', title: 'Bordetella pertussis', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Respiratory Tract', title: 'Haemophilus influenzae', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Respiratory Tract', title: 'Legionella pneumophila', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Respiratory Tract', title: 'Pseudomonas aeruginosa', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Respiratory Tract', title: 'Burkholderia pseudomallei & cepacia complex', watched: false),
  // GN Bacilli Zoonotics
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Zoonotics', title: 'Bartonella henselae', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Zoonotics', title: 'Brucella spp.', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Zoonotics', title: 'Francisella tularensis', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Zoonotics', title: 'Pasteurella multocida', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Negative Bacilli: Zoonotics', title: 'Anaplasma phagocytophilum & Ehrlichia chaffeensis', watched: false),
  // Mycobacteria
  SketchyVideo(category: 'Bacteria', subcategory: 'Mycobacteria', title: 'Mycobacterium tuberculosis', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Mycobacteria', title: 'Mycobacterium leprae', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Mycobacteria', title: 'Mycobacterium avium intracellulare, M. scrofulaceum, M. marinum', watched: false),
  // Spirochetes
  SketchyVideo(category: 'Bacteria', subcategory: 'Spirochetes', title: 'Borrelia burgdorferi', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Spirochetes', title: 'Borrelia recurrentis', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Spirochetes', title: 'Leptospira interrogans', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Spirochetes', title: 'Treponema pallidum', watched: false),
  // Gram-Indeterminate
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Indeterminate Bacteria', title: 'Chlamydia trachomatis, Chlamydophila pneumoniae & psittaci', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Indeterminate Bacteria', title: 'Coxiella burnetii', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Indeterminate Bacteria', title: 'Gardnerella vaginalis', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Indeterminate Bacteria', title: 'Mycoplasma pneumoniae', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Indeterminate Bacteria', title: 'Rickettsia Overview', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Indeterminate Bacteria', title: 'Rickettsia prowazekii', watched: false),
  SketchyVideo(category: 'Bacteria', subcategory: 'Gram-Indeterminate Bacteria', title: 'Rickettsia rickettsii', watched: false),
  // FUNGI
  SketchyVideo(category: 'Fungi', subcategory: 'Systemic Mycoses', title: 'Histoplasma capsulatum', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Systemic Mycoses', title: 'Blastomyces dermatitidis', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Systemic Mycoses', title: 'Coccidioides immitis', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Systemic Mycoses', title: 'Paracoccidioides brasiliensis', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Cutaneous Mycoses', title: 'Malassezia furfur', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Cutaneous Mycoses', title: 'Dermatophytes – Epidermophyton, Trichophyton, Microsporum', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Cutaneous Mycoses', title: 'Sporothrix schenckii', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Opportunistic Fungal Infections', title: 'Candida albicans', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Opportunistic Fungal Infections', title: 'Aspergillus fumigatus', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Opportunistic Fungal Infections', title: 'Cryptococcus neoformans', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Opportunistic Fungal Infections', title: 'Mucor spp. & Rhizopus spp. – Mucormycetes', watched: false),
  SketchyVideo(category: 'Fungi', subcategory: 'Opportunistic Fungal Infections', title: 'Pneumocystis jirovecii', watched: false),
  // VIRUSES — RNA Positive Sense
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Picornaviridae Overview', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Poliovirus – Picornaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Coxsackievirus A & B – Picornaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Rhinovirus – Picornaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Hepatitis A Virus – Picornaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Norovirus & Norwalk Virus – Calciviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Flaviviridae Overview', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Hepatitis C Virus – Flaviviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Coronavirus – Coronaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Equine Encephalitis Viruses & Chikungunya – Togaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'Rubella Virus – Matonaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'HIV Overview – Retroviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Positive Sense', title: 'HIV Life Cycle – Retroviridae', watched: false),
  // RNA Negative Sense
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Negative Sense', title: 'Influenzavirus – Orthomyxoviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Negative Sense', title: 'Measles, Mumps, Parainfluenza – Paramyxoviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Negative Sense', title: 'Respiratory Syncytial Virus & Human Metapneumovirus', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Negative Sense', title: 'Rabies Virus – Rhabdoviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Negative Sense', title: 'Ebolavirus & Marburgvirus – Filoviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Negative Sense', title: 'Hantavirus, California Encephalitis, Rift Valley Fever – Bunyaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Negative Sense', title: 'Lymphocytic Choriomeningitis Virus – Arenaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'RNA Viruses: Negative Sense', title: 'Rotavirus & Colorado Tick Fever Virus – Reoviridae', watched: false),
  // DNA Viruses
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Herpes Simplex Virus 1 & 2 – Herpesviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Epstein-Barr Virus – Herpesviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Cytomegalovirus – Herpesviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Varicella-Zoster Virus – Herpesviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'HHV-6 & Roseola – Herpesviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: "HHV-8 & Kaposi's Sarcoma – Herpesviridae", watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'JC Polyomavirus & BK Polyomavirus', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Human Papillomavirus – Papillomaviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Parvovirus B19 – Parvoviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Adenovirus – Adenoviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Smallpox, Cowpox, Molluscum Contagiosum – Poxviridae', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Hepatitis B Viral Basics & Infectious Diseases', watched: false),
  SketchyVideo(category: 'Viruses', subcategory: 'DNA Viruses', title: 'Hepatitis B Viral Life Cycle – Hepadnaviridae', watched: false),
  // PARASITES
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the Intestinal Tract', title: 'Giardia lamblia', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the Intestinal Tract', title: 'Entamoeba histolytica', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the Intestinal Tract', title: 'Cryptosporidium spp.', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the CNS', title: 'Toxoplasma gondii', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the CNS', title: 'Trypanosoma brucei', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the CNS', title: 'Naegleria fowleri', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the Blood', title: 'Trypanosoma cruzi', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the Blood', title: 'Babesia spp.', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the Blood', title: 'Plasmodium: Infection & Lifecycle', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the Blood', title: 'Plasmodium: Treatment & PPX', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa of the Blood', title: 'Leishmania braziliensis & donovani', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Protozoa: Other Tissue', title: 'Trichomonas vaginalis', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Helminths: Nematodes', title: 'Intestinal Nematodes: Enterobius, Ancylostoma, Necator, Ascaris, Strongyloides, Trichinella', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Helminths: Nematodes', title: 'Tissue Nematodes: Dracunculus, Wuchereria, Onchocerca, Toxocara, Loa loa', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Helminths: Trematodes & Cestodes', title: 'Cestodes', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Helminths: Trematodes & Cestodes', title: 'Trematodes', watched: false),
  SketchyVideo(category: 'Parasites', subcategory: 'Ectoparasites', title: 'Scabies, Lice, Crabs', watched: false),
];
