import '../models/sketchy_video.dart';

final List<SketchyVideo> sketchyPharmSeed = [
  // AUTONOMIC DRUGS
  SketchyVideo(category: 'Autonomic Drugs', subcategory: 'Parasympathetic', title: 'Cholinomimetics', watched: false),
  SketchyVideo(category: 'Autonomic Drugs', subcategory: 'Parasympathetic', title: 'Acetylcholinesterase Inhibitors', watched: false),
  SketchyVideo(category: 'Autonomic Drugs', subcategory: 'Parasympathetic', title: 'Muscarinic Antagonists', watched: false),
  SketchyVideo(category: 'Autonomic Drugs', subcategory: 'Sympathetic', title: 'Sympathomimetics', watched: false),
  SketchyVideo(category: 'Autonomic Drugs', subcategory: 'Sympathetic', title: 'Indirect Sympathomimetics', watched: false),
  SketchyVideo(category: 'Autonomic Drugs', subcategory: 'Sympathetic', title: 'Alpha Drugs', watched: false),
  SketchyVideo(category: 'Autonomic Drugs', subcategory: 'Sympathetic', title: 'Beta Blockers', watched: false),
  // CARDIO & RENAL
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Heart Failure Drugs', title: 'Digoxin', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Heart Failure Drugs', title: 'ACE Inhibitors, ARBs, Aliskiren', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Heart Failure Drugs', title: 'Sacubitril-Valsartan, Milrinone, Nesiritide, Ivabradine', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Diuretics', title: 'Acetazolamide & Mannitol', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Diuretics', title: 'Loop Diuretics', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Diuretics', title: 'Thiazides', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Diuretics', title: 'Potassium-Sparing Diuretics', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Antihypertensives', title: 'Calcium Channel Blockers', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Antihypertensives', title: 'Primary Hypertension & Hypertensive Emergency', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Antiarrhythmics', title: 'Class I A-C Antiarrhythmics', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Antiarrhythmics', title: 'Class II Antiarrhythmics', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Antiarrhythmics', title: 'Class III Antiarrhythmics', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Antiarrhythmics', title: 'Class IV Antiarrhythmics', watched: false),
  SketchyVideo(category: 'Cardio & Renal', subcategory: 'Antiarrhythmics', title: 'Class V Antiarrhythmics', watched: false),
  // BLOOD & INFLAMMATION
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Anticoagulants & Thrombolytics', title: 'Heparin, LMWH, Fondaparinux, Direct Thrombin & Xa Inhibitors', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Anticoagulants & Thrombolytics', title: 'Warfarin', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Anticoagulants & Thrombolytics', title: 'Antiplatelet Agents', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Anticoagulants & Thrombolytics', title: 'Thrombolytics', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Dyslipidemia Drugs', title: 'Statins', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Dyslipidemia Drugs', title: 'Cholestyramine & Ezetimibe', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Dyslipidemia Drugs', title: 'Fibrates & Niacin', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Dyslipidemia Drugs', title: 'PCSK9 Inhibitors', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Anti-Inflammatory', title: 'NSAIDs', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Anti-Inflammatory', title: 'Gout Drugs', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Anti-Inflammatory', title: 'Immunosuppressants', watched: false),
  SketchyVideo(category: 'Blood & Inflammation', subcategory: 'Anti-Inflammatory', title: 'TNF Inhibitors', watched: false),
  // SMOOTH MUSCLE
  SketchyVideo(category: 'Smooth Muscle', subcategory: 'Vasoactive', title: 'Nitrates', watched: false),
  SketchyVideo(category: 'Smooth Muscle', subcategory: 'Vasoactive', title: 'Triptans & Migraine', watched: false),
  SketchyVideo(category: 'Smooth Muscle', subcategory: 'Vasoactive', title: 'Prostaglandins, Prostacyclin, Bosentan, PDE5 Inhibitors', watched: false),
  SketchyVideo(category: 'Smooth Muscle', subcategory: 'Allergy & Pulmonary', title: 'Antihistamines', watched: false),
  SketchyVideo(category: 'Smooth Muscle', subcategory: 'Allergy & Pulmonary', title: 'Asthma Therapy', watched: false),
  // GI & ENDOCRINE
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'GI', title: 'Antiemetic Agents', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'GI', title: 'H2 Receptor Blockers & PPIs', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'GI', title: 'Laxatives', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'GI', title: 'Antidiarrheal Agents', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Diabetes', title: 'Insulin, Sulfonylureas, Meglitinides, GLP-1 Agonists, DPP-4 Inhibitors', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Diabetes', title: 'Metformin, Thiazolidinediones, Pramlintide, SGLT2 Inhibitors', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Thyroid, Parathyroid, Adrenal', title: 'Propylthiouracil, Methimazole, Levothyroxine', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Thyroid, Parathyroid, Adrenal', title: 'Bisphosphonates, Raloxifene, Denosumab, Calcitonin', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Thyroid, Parathyroid, Adrenal', title: 'Teriparatide, Vitamin D, Cinacalcet, Sevelamer', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Thyroid, Parathyroid, Adrenal', title: 'Glucocorticoids', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Hypothalamic & Pituitary', title: 'Growth Hormone, Mecasermin, Octreotide, Pegvisomant', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Hypothalamic & Pituitary', title: 'ADH, DDAVP, ADH Receptor Antagonists', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Sex Hormones', title: 'SERMs & Aromatase Inhibitors', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Sex Hormones', title: 'LHRH Agonists/GnRH Analogs', watched: false),
  SketchyVideo(category: 'GI & Endocrine', subcategory: 'Sex Hormones', title: 'Non-Steroidal Antiandrogens (NSAAs)', watched: false),
  // NEURO & PSYCH
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Anesthetics & Analgesics', title: 'IV Anesthetics', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Anesthetics & Analgesics', title: 'Inhaled Anesthetics & Dantrolene', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Anesthetics & Analgesics', title: 'Opioids, Naloxone, Naltrexone', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Antidepressants & Anxiolytics', title: 'SSRIs, SNRIs, Cyproheptadine', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Antidepressants & Anxiolytics', title: 'Tricyclic Antidepressants', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Antidepressants & Anxiolytics', title: 'MAO Inhibitors', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Antidepressants & Anxiolytics', title: 'Bupropion, Mirtazapine, Trazodone', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Antidepressants & Anxiolytics', title: 'Buspirone', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Mood Stabilizers & Antiepileptic Drugs', title: 'Lithium', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Mood Stabilizers & Antiepileptic Drugs', title: 'Broad-Spectrum Antiepileptics', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Mood Stabilizers & Antiepileptic Drugs', title: 'Ethosuximide', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Mood Stabilizers & Antiepileptic Drugs', title: 'Carbamazepine, Oxcarbazepine, Phenytoin, Tiagabine, Vigabatrin', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Mood Stabilizers & Antiepileptic Drugs', title: 'Gabapentin & Pregabalin', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: "Antipsychotics & Parkinson's", title: 'First-Generation Antipsychotics', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: "Antipsychotics & Parkinson's", title: 'Second-Generation Antipsychotics', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: "Antipsychotics & Parkinson's", title: 'Parkinsonism Drugs', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Psychostimulants: Narcolepsy & ADHD', title: 'Narcolepsy Drugs', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Psychostimulants: Narcolepsy & ADHD', title: 'Amphetamine, Dexamphetamine, Lisdexamfetamine, Methylphenidate', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Sedative-Hypnotics', title: 'Benzodiazepines & Flumazenil', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Sedative-Hypnotics', title: 'Nonbenzodiazepine Hypnotics, Melatonin, Ramelteon', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Sedative-Hypnotics', title: 'Barbiturates', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Smoking Cessation Aids', title: 'Varenicline', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: 'Muscle Relaxants', title: 'Skeletal Muscle Relaxants', watched: false),
  SketchyVideo(category: 'Neuro & Psych', subcategory: "Alzheimer's Meds", title: "Alzheimer's Disease Medications", watched: false),
  // ANTIMICROBIALS
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Cell Wall & Membrane-Active Antibiotics', title: 'Penicillin', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Cell Wall & Membrane-Active Antibiotics', title: 'Nafcillin, Oxacillin, Methicillin, Dicloxacillin', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Cell Wall & Membrane-Active Antibiotics', title: 'Ampicillin, Amoxicillin, Piperacillin, Ticarcillin', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Cell Wall & Membrane-Active Antibiotics', title: 'Cephalosporins', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Cell Wall & Membrane-Active Antibiotics', title: 'Monobactams & Carbapenems', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Cell Wall & Membrane-Active Antibiotics', title: 'Vancomycin', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Cell Wall & Membrane-Active Antibiotics', title: 'Daptomycin', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Inhibitors of Bacterial Protein Synthesis', title: 'Tetracyclines', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Inhibitors of Bacterial Protein Synthesis', title: 'Macrolides', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Inhibitors of Bacterial Protein Synthesis', title: 'Clindamycin', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Inhibitors of Bacterial Protein Synthesis', title: 'Chloramphenicol', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Inhibitors of Bacterial Protein Synthesis', title: 'Linezolid', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Inhibitors of Bacterial Protein Synthesis', title: 'Aminoglycosides', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Antimycobacterials', title: 'Tuberculosis Drugs', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Antimycobacterials', title: 'Leprosy Drugs', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Other Antibiotics', title: 'Trimethoprim/Sulfamethoxazole', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Other Antibiotics', title: 'Fluoroquinolones', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Other Antibiotics', title: 'Metronidazole', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Antifungals', title: 'Amphotericin & Flucytosine', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Antifungals', title: 'Azoles', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Antifungals', title: 'Griseofulvin, Terbinafine, Echinocandins', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'HIV Antivirals', title: 'NRTIs', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'HIV Antivirals', title: 'NNRTIs', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'HIV Antivirals', title: 'Protease Inhibitors', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'HIV Antivirals', title: 'Maraviroc, Fusion Inhibitors, Integrase Inhibitors', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Other Antivirals', title: 'Acyclovir, Valacyclovir, Famciclovir', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Other Antivirals', title: 'Hepatitis C: Direct-Acting Antivirals (DAAs)', watched: false),
  SketchyVideo(category: 'Antimicrobials', subcategory: 'Other Antivirals', title: 'Ganciclovir, Valganciclovir, Foscarnet, Cidofovir', watched: false),
  // ANTINEOPLASTICS
  SketchyVideo(category: 'Antineoplastics', subcategory: 'Antimetabolites', title: 'Methotrexate, Leucovorin, 5-Fluorouracil, Hydroxyurea', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'Antimetabolites', title: 'Azathioprine, 6-Mercaptopurine, Mycophenolate Mofetil', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'Antimetabolites', title: 'Cytotoxic Nucleoside Analogs', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'DNA & Cellular Division', title: 'Alkylating Agents', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'DNA & Cellular Division', title: 'Platins', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'DNA & Cellular Division', title: 'Cytotoxic Antibiotics', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'DNA & Cellular Division', title: 'Topoisomerase Inhibitors', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'DNA & Cellular Division', title: 'Mitotic Inhibitors', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'Kinase Inhibitors & Monoclonal Antibodies', title: 'Kinase Inhibitors', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'Kinase Inhibitors & Monoclonal Antibodies', title: 'Monoclonal Antibody Therapy', watched: false),
  SketchyVideo(category: 'Antineoplastics', subcategory: 'Immunology', title: 'Interferons', watched: false),
  // PHARM FOUNDATIONS
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Pharmacokinetic Basics', title: 'Membranes: Partition Coefficient, Passive Diffusion, Active Transport', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Pharmacokinetic Basics', title: 'Plasma Concentration & Therapeutic Range', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Absorption', title: 'Oral Drug Absorption & Bioavailability/F', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Absorption', title: 'Intro to Drug Absorption via Parenteral Routes', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Distribution', title: 'Drug Distribution & Protein Binding', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Distribution', title: 'Volume of Distribution', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Metabolism', title: 'Intro to CYP450 Enzymes', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Metabolism', title: 'P-Glycoprotein & Enterohepatic Recycling', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Elimination', title: 'Clearance & Area Under the Curve', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Elimination', title: 'Elimination-Rate Constant, Half-Life, Steady State', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Pharmacodynamic Basics', title: 'Agonists, Antagonists, Allosteric Modulators', watched: false),
  SketchyVideo(category: 'Pharm Foundations', subcategory: 'Drug-Drug Interactions', title: 'Intro to Pharmacodynamic & Pharmacokinetic Drug Interactions', watched: false),
];
