import 'package:focusflow_mobile/utils/constants.dart';

class TaskSuggestion {
  final String emoji;
  final BlockType category;
  final String colorHex;

  const TaskSuggestion({
    required this.emoji,
    required this.category,
    required this.colorHex,
  });
}

class TaskSuggestionsService {
  static const TaskSuggestion _studySuggestion = TaskSuggestion(
    emoji: '\u{1F4DA}',
    category: BlockType.studySession,
    colorHex: '#4A90D9',
  );

  static const TaskSuggestion _videoSuggestion = TaskSuggestion(
    emoji: '\u{1F4DA}',
    category: BlockType.video,
    colorHex: '#4A90D9',
  );

  static const TaskSuggestion _revisionSuggestion = TaskSuggestion(
    emoji: '\u{1F4DA}',
    category: BlockType.revisionFa,
    colorHex: '#4A90D9',
  );

  static const TaskSuggestion _ankiSuggestion = TaskSuggestion(
    emoji: '\u{1F4DA}',
    category: BlockType.anki,
    colorHex: '#4A90D9',
  );

  static const TaskSuggestion _qbankSuggestion = TaskSuggestion(
    emoji: '\u{1F4DA}',
    category: BlockType.qbank,
    colorHex: '#4A90D9',
  );

  static const TaskSuggestion _medicalExamSuggestion = TaskSuggestion(
    emoji: '\u{1F4DA}',
    category: BlockType.fmgeRevision,
    colorHex: '#4A90D9',
  );

  static const TaskSuggestion _workSuggestion = TaskSuggestion(
    emoji: '\u{1F4BC}',
    category: BlockType.other,
    colorHex: '#5856D6',
  );

  static const TaskSuggestion _healthSuggestion = TaskSuggestion(
    emoji: '\u{1F3CB}',
    category: BlockType.other,
    colorHex: '#30D158',
  );

  static const TaskSuggestion _mealSuggestion = TaskSuggestion(
    emoji: '\u{1F37D}',
    category: BlockType.breakBlock,
    colorHex: '#FF9F0A',
  );

  static const TaskSuggestion _prayerSuggestion = TaskSuggestion(
    emoji: '\u{1F54C}',
    category: BlockType.other,
    colorHex: '#BF5AF2',
  );

  static const TaskSuggestion _personalSuggestion = TaskSuggestion(
    emoji: '\u{1F3E0}',
    category: BlockType.other,
    colorHex: '#FF6B6B',
  );

  static const TaskSuggestion _leisureSuggestion = TaskSuggestion(
    emoji: '\u{1F389}',
    category: BlockType.other,
    colorHex: '#FF9F0A',
  );

  static const TaskSuggestion _nightSuggestion = TaskSuggestion(
    emoji: '\u{1F319}',
    category: BlockType.other,
    colorHex: '#1C1C1E',
  );

  static const TaskSuggestion _defaultSuggestion = TaskSuggestion(
    emoji: '\u{2728}',
    category: BlockType.other,
    colorHex: '#E8837A',
  );

  static final List<_KeywordRule> _rules = _buildRules();

  static TaskSuggestion suggest(String input) {
    final normalizedInput = _normalize(input);
    if (normalizedInput.isEmpty) {
      return _defaultSuggestion;
    }

    _KeywordRule? bestMatch;
    for (final rule in _rules) {
      if (!normalizedInput.contains(rule.keyword)) {
        continue;
      }
      if (bestMatch == null || rule.keyword.length > bestMatch.keyword.length) {
        bestMatch = rule;
      }
    }

    return bestMatch?.suggestion ?? _defaultSuggestion;
  }

  static List<_KeywordRule> _buildRules() {
    final rules = <_KeywordRule>[];
    final seen = <String>{};

    void addAll(TaskSuggestion suggestion, List<String> keywords) {
      for (final rawKeyword in keywords) {
        final keyword = _normalize(rawKeyword);
        if (keyword.isEmpty || !seen.add(keyword)) {
          continue;
        }
        rules.add(_KeywordRule(keyword: keyword, suggestion: suggestion));
      }
    }

    addAll(_medicalExamSuggestion, _medicalExamKeywords);
    addAll(_ankiSuggestion, _ankiKeywords);
    addAll(_qbankSuggestion, _qbankKeywords);
    addAll(_videoSuggestion, _videoKeywords);
    addAll(_revisionSuggestion, _revisionKeywords);
    addAll(_studySuggestion, _studyKeywords);
    addAll(_workSuggestion, _workKeywords);
    addAll(_healthSuggestion, _healthKeywords);
    addAll(_mealSuggestion, _mealKeywords);
    addAll(_prayerSuggestion, _prayerKeywords);
    addAll(_personalSuggestion, _personalKeywords);
    addAll(_leisureSuggestion, _leisureKeywords);
    addAll(_nightSuggestion, _nightKeywords);

    return List.unmodifiable(rules);
  }

  static String _normalize(String input) {
    return input
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]+'), ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  static const List<String> _medicalExamKeywords = [
    'usmle',
    'usmle step 1',
    'usmle step1',
    'usmle step 2',
    'usmle step2',
    'usmle step 2 ck',
    'step 1 prep',
    'step1 prep',
    'step 2 prep',
    'step2 prep',
    'step 2 ck',
    'step2ck',
    'ck prep',
    'fmge',
    'fmge prep',
    'fmge revision',
    'neet pg',
    'neetpg',
    'inicet',
    'plab',
    'mccqe',
    'residency prep',
    'internship study',
    'clerkship',
    'clerkship prep',
    'rotation',
    'medicine rotation',
    'surgery rotation',
    'obgyn rotation',
    'peds rotation',
    'pediatric rotation',
    'psych rotation',
    'family medicine rotation',
    'internal medicine rotation',
    'ward prep',
    'ward round',
    'rounds prep',
    'case discussion',
    'case presentation',
    'grand rounds',
    'patient note',
    'soap note',
    'history taking',
    'physical exam',
    'clinical skills',
    'clinical case',
    'clinical posting',
    'clinical reasoning',
    'shelf',
    'shelf prep',
    'shelf review',
    'shelf exam',
    'nbme review',
    'osce',
    'osce prep',
    'viva',
    'viva prep',
    'spotter',
    'spotters',
    'prof exam',
    'profs',
    'mbbs',
    'mbbs study',
    'housejob study',
  ];

  static const List<String> _ankiKeywords = [
    'anki',
    'anki review',
    'anki session',
    'anki block',
    'anki deck',
    'do anki',
    'zanki',
    'zanki deck',
    'anking',
    'anking deck',
    'flashcards',
    'flashcard',
    'flash card',
    'flash card review',
    'review flashcards',
    'review cards',
    'card review',
    'card reps',
    'cards',
    'new cards',
    'due cards',
    'deck review',
    'review deck',
    'spaced repetition',
    'srs',
    'revise cards',
    'deck due',
  ];

  static const List<String> _qbankKeywords = [
    'uworld',
    'u world',
    'uworld block',
    'uworld review',
    'amboss',
    'amboss questions',
    'qbank',
    'question bank',
    'question block',
    'practice questions',
    'question practice',
    'questions',
    'solve questions',
    'mcq',
    'mcqs',
    'solve mcqs',
    'bank review',
    'review explanations',
    'timed block',
    'untimed block',
    'nbme',
    'nbmes',
    'cms form',
    'cms forms',
    'usmle rx',
    'rx qbank',
    'exam questions',
    'test questions',
    'practice test',
    'practice exam',
    'mock test',
    'mock exam',
    'sample paper',
    'previous year questions',
    'past papers',
    'pyq',
    'solve blocks',
    'qb session',
    'attempt questions',
    'case questions',
    'question session',
    'quiz questions',
    'saq',
    'vignette questions',
    'nbme block',
    'amboss block',
  ];

  static const List<String> _videoKeywords = [
    'video lecture',
    'watch lecture',
    'watch class',
    'watch video',
    'lecture video',
    'lecture videos',
    'recorded lecture',
    'course video',
    'youtube lecture',
    'youtube class',
    'lecture recording',
    'watch recording',
    'online lecture',
    'tutorial video',
    'demo video',
    'module video',
    'coaching video',
    'webinar',
    'watch pathoma',
    'watch sketchy',
    'watch bnb',
    'boards and beyond',
    'bnb',
    'b and b',
    'pathoma',
    'sketchy',
    'sketchy micro',
    'sketchy pharm',
    'osmosis',
    'pixorize',
    'kaplan video',
    'bootcamp video',
    'dirty medicine',
    'watch replay',
    'video class',
    'lecture replay',
  ];

  static const List<String> _revisionKeywords = [
    'first aid',
    'first aid pages',
    'fa pages',
    'fa review',
    'fa reading',
    'fa revision',
    'revise fa',
    'rapid review',
    'quick review',
    'read notes',
    'review notes',
    'note review',
    'notebook review',
    'annotate notes',
    'margin notes',
    'book review',
    'chapter review',
    'revise chapter',
    'high yield review',
    'one shot review',
    'condense notes',
    'review notebook',
    'annotate first aid',
    'read textbook',
    'page review',
    'pdf review',
    'handwritten notes',
    'summary review',
    'quick read',
    'reread',
    're read',
    'read over',
    'skim notes',
    'skim chapter',
    'revise notes',
    'revision session',
    'revision',
    'revise',
  ];

  static const List<String> _studyKeywords = [
    'study',
    'studying',
    'study time',
    'study session',
    'study block',
    'self study',
    'group study',
    'focus study',
    'deep study',
    'homework',
    'assignment',
    'assignments',
    'worksheet',
    'worksheets',
    'problem set',
    'problem sets',
    'practice set',
    'practice problems',
    'essay',
    'paper',
    'report',
    'reading',
    'read chapter',
    'chapter reading',
    'textbook',
    'lecture',
    'lectures',
    'class',
    'classes',
    'tutorial',
    'tutorials',
    'seminar',
    'seminars',
    'lab',
    'lab work',
    'lab report',
    'practical',
    'practicals',
    'quiz prep',
    'test prep',
    'exam prep',
    'midterm prep',
    'final prep',
    'review',
    'notes',
    'note making',
    'summary',
    'summarize',
    'summarise',
    'memorize',
    'memorise',
    'concept review',
    'office hours',
    'research',
    'case study',
    'presentation prep',
    'project work',
    'thesis',
    'dissertation',
    'coursework',
    'module review',
    'learning',
    'learn topic',
    'pomodoro study',
    'focus session',
    'math',
    'maths',
    'algebra',
    'geometry',
    'trigonometry',
    'trig',
    'calculus',
    'calc',
    'statistics',
    'stats',
    'probability',
    'linear algebra',
    'discrete math',
    'data structures',
    'algorithms',
    'physics',
    'mechanics',
    'thermodynamics',
    'optics',
    'electricity',
    'magnetism',
    'chemistry',
    'chem',
    'organic chemistry',
    'ochem',
    'inorganic chemistry',
    'physical chemistry',
    'biochemistry',
    'biochem',
    'biology',
    'bio',
    'botany',
    'zoology',
    'genetics',
    'microbiology',
    'anatomy',
    'physiology',
    'pathology',
    'path',
    'pharmacology',
    'pharm',
    'immunology',
    'histology',
    'embryology',
    'neuroscience',
    'neurology',
    'medicine',
    'surgery',
    'pediatrics',
    'peds',
    'obgyn',
    'obstetrics',
    'gynecology',
    'dermatology',
    'ent',
    'ophthalmology',
    'radiology',
    'cardiology',
    'nephrology',
    'gastroenterology',
    'pulmonology',
    'endocrinology',
    'hematology',
    'oncology',
    'psychiatry',
    'orthopedics',
    'ortho',
    'community medicine',
    'psm',
    'epidemiology',
    'public health',
    'biostatistics',
    'history',
    'geography',
    'economics',
    'econ',
    'english',
    'literature',
    'grammar',
    'writing',
    'computer science',
    'programming course',
    'coding practice',
    'data science',
    'machine learning',
    'artificial intelligence',
    'accounting',
    'finance study',
    'law study',
    'civics',
    'political science',
    'sociology',
    'psychology',
    'philosophy',
    'language practice',
    'spanish',
    'french',
    'german',
    'arabic',
    'urdu',
    'hindi',
  ];

  static const List<String> _workKeywords = [
    'work',
    'work session',
    'office',
    'job',
    'client work',
    'meeting',
    'meetings',
    'team meeting',
    'client meeting',
    'standup',
    'daily standup',
    'one on one',
    '1 on 1',
    'sync',
    'team sync',
    'planning',
    'sprint planning',
    'retro',
    'retrospective',
    'brainstorm',
    'proposal',
    'pitch deck',
    'slides',
    'presentation',
    'presentation work',
    'reporting',
    'status report',
    'admin work',
    'paperwork',
    'emails',
    'email',
    'reply emails',
    'follow up',
    'follow-up',
    'inbox',
    'slack',
    'teams message',
    'discord work',
    'documentation',
    'docs',
    'write docs',
    'spec',
    'prd',
    'roadmap',
    'backlog',
    'jira',
    'ticket',
    'tickets',
    'bug fix',
    'bugfix',
    'debug',
    'debugging',
    'deploy',
    'deployment',
    'release',
    'ship release',
    'code review',
    'review pr',
    'pull request',
    'merge pr',
    'coding',
    'programming',
    'build feature',
    'implement feature',
    'feature work',
    'dev work',
    'development',
    'frontend',
    'backend',
    'api work',
    'database work',
    'db work',
    'testing',
    'write tests',
    'fix tests',
    'refactor',
    'refactoring',
    'design review',
    'ux review',
    'figma',
    'notion',
    'calendar',
    'plan day',
    'time block',
    'timeboxing',
    'pomodoro',
    'focus',
    'focus block',
    'deep work',
    'flow session',
    'task block',
    'session',
    'catch up',
    'forms',
    'compliance',
    'training',
    'interview prep',
    'portfolio',
    'resume',
    'cv update',
    'job application',
    'apply jobs',
    'freelance',
    'invoice',
    'timesheet',
    'submit timesheet',
    'expense report',
    'business plan',
    'marketing',
    'content planning',
    'analytics',
    'seo',
    'sales call',
    'client call',
    'vendor call',
    'ops work',
  ];

  static const List<String> _healthKeywords = [
    'gym',
    'workout',
    'exercise',
    'train',
    'training',
    'lift',
    'lifting',
    'weights',
    'strength training',
    'cardio',
    'run',
    'running',
    'jog',
    'jogging',
    'walk',
    'walking',
    'steps',
    'step goal',
    'treadmill',
    'cycling',
    'bike ride',
    'spin',
    'elliptical',
    'swim',
    'swimming',
    'yoga',
    'pilates',
    'stretch',
    'stretching',
    'mobility',
    'warm up',
    'warmup',
    'cool down',
    'cooldown',
    'hiit',
    'crossfit',
    'sports practice',
    'football',
    'soccer',
    'basketball',
    'tennis',
    'badminton',
    'cricket',
    'volleyball',
    'table tennis',
    'ping pong',
    'golf',
    'baseball',
    'hockey',
    'skating',
    'martial arts',
    'boxing',
    'kickboxing',
    'mma',
    'karate',
    'taekwondo',
    'wrestling',
    'bjj',
    'jiu jitsu',
    'meditate',
    'meditation',
    'breathing',
    'breathwork',
    'therapy',
    'counselling',
    'counseling',
    'doctor',
    'clinic',
    'dentist',
    'physio',
    'physiotherapy',
    'rehab',
    'recovery',
    'nap',
    'rest',
    'hydration',
    'drink water',
    'water break',
    'supplements',
    'vitamins',
    'protein shake',
    'protein',
  ];

  static const List<String> _mealKeywords = [
    'breakfast',
    'lunch',
    'dinner',
    'meal',
    'meals',
    'meal prep',
    'meal planning',
    'food prep',
    'prep food',
    'cooking',
    'cook',
    'cook dinner',
    'cook lunch',
    'cook breakfast',
    'make food',
    'eat',
    'eating',
    'snack',
    'snacks',
    'tea',
    'coffee',
    'chai',
    'brunch',
    'supper',
    'iftar',
    'suhoor',
    'sehri',
    'pre workout meal',
    'post workout meal',
    'smoothie',
    'juice',
    'pack lunch',
    'packed lunch',
    'heat food',
    'reheat food',
    'wash produce',
    'cut veggies',
    'chop vegetables',
    'make salad',
    'boil eggs',
    'make eggs',
    'rice',
    'dal',
    'roti',
    'chapati',
    'meal break',
    'lunch break',
    'dinner break',
    'breakfast break',
    'bake',
    'grill',
    'fry',
    'saute',
    'steam food',
    'grocery cooking',
    'marinate',
    'meal cleanup',
    'do dishes',
    'kitchen cleanup',
    'order food',
    'takeout',
    'restaurant',
    'eat out',
    'dining',
    'dessert',
    'drink tea',
    'drink coffee',
    'prep snack',
    'fruit break',
    'protein meal',
    'lunch prep',
    'dinner prep',
  ];

  static const List<String> _prayerKeywords = [
    'prayer',
    'pray',
    'namaz',
    'salah',
    'salat',
    'fajr',
    'zuhr',
    'dhuhr',
    'asr',
    'maghrib',
    'isha',
    'tahajjud',
    'witr',
    'jummah',
    'jumuah',
    'dua',
    'dhikr',
    'zikr',
    'tasbeeh',
    'quran',
    'quran recitation',
    'read quran',
    'surah',
    'hadith',
    'islamic lecture',
    'church',
    'mass',
    'bible',
    'read bible',
    'bible study',
    'devotion',
    'devotional',
    'rosary',
    'chaplet',
    'vespers',
    'matins',
    'communion',
    'confession',
    'temple',
    'puja',
    'pooja',
    'aarti',
    'darshan',
    'jap',
    'jaap',
    'mantra',
    'chant',
    'satsang',
    'seva',
    'path',
    'paath',
    'gurbani',
    'nitnem',
    'simran',
    'waheguru',
    'guru granth sahib',
    'sikh prayer',
    'buddhist chanting',
    'zen',
    'mindfulness prayer',
    'shabbat',
    'torah',
    'synagogue',
    'mincha',
    'maariv',
    'shiv puja',
    'hanuman chalisa',
  ];

  static const List<String> _personalKeywords = [
    'clean',
    'cleaning',
    'room clean',
    'tidy room',
    'organize room',
    'organise room',
    'declutter',
    'laundry',
    'wash clothes',
    'fold clothes',
    'iron clothes',
    'bath',
    'shower',
    'hair wash',
    'skincare',
    'skin care',
    'haircut',
    'grooming',
    'brush teeth',
    'floss',
    'make bed',
    'change sheets',
    'vacuum',
    'sweep',
    'mop',
    'dusting',
    'trash',
    'take out trash',
    'dishes',
    'dishwashing',
    'kitchen clean',
    'bathroom clean',
    'toilet clean',
    'shopping',
    'grocery',
    'groceries',
    'market',
    'buy groceries',
    'pharmacy',
    'chemist',
    'pick up meds',
    'pickup meds',
    'collect parcel',
    'pick up package',
    'courier',
    'post office',
    'bank',
    'atm',
    'pay bills',
    'bill payment',
    'recharge',
    'phone recharge',
    'utility bill',
    'insurance',
    'documents',
    'paperwork errand',
    'aadhaar',
    'passport',
    'license',
    'id card',
    'renew license',
    'car service',
    'fuel',
    'petrol',
    'gas up',
    'garage',
    'repair',
    'maintenance',
    'household',
    'baby care',
    'pet care',
    'dog walk',
    'cat litter',
    'vet',
    'doctor appointment',
    'appointment',
    'salon',
    'barber',
    'tailor',
    'gift shopping',
    'buy gift',
    'return order',
    'exchange order',
    'amazon return',
    'errands',
    'chores',
    'home task',
    'family time',
    'parent call',
    'call mom',
    'call dad',
    'school pickup',
    'drop off',
    'pickup',
    'dropoff',
    'commute',
    'travel to office',
    'bus',
    'metro',
    'train ride',
    'drive',
    'cab',
    'uber',
    'ola',
    'taxes',
    'tax filing',
    'rent payment',
    'emi payment',
  ];

  static const List<String> _leisureKeywords = [
    'hangout',
    'hang out',
    'friends',
    'meet friends',
    'date',
    'date night',
    'movie',
    'watch movie',
    'cinema',
    'netflix',
    'youtube',
    'web series',
    'gaming',
    'game',
    'playstation',
    'xbox',
    'switch game',
    'pc game',
    'board game',
    'music',
    'listen music',
    'concert',
    'party',
    'celebration',
    'birthday',
    'wedding',
    'reception',
    'picnic',
    'outing',
    'beach',
    'mall',
    'shopping trip',
    'cafe',
    'coffee with friends',
    'dinner with friends',
    'lunch with friends',
    'call friend',
    'video call',
    'chat',
    'catch up with friends',
    'family dinner',
    'family outing',
    'visit relatives',
    'guest visit',
    'social event',
    'club',
    'karaoke',
    'dance',
    'dance class',
    'art class',
    'painting',
    'paint',
    'draw',
    'drawing',
    'guitar',
    'piano',
    'singing',
    'photography',
    'photo walk',
    'reading novel',
    'novel',
    'comic',
    'manga',
    'anime',
    'podcast',
    'garden',
    'gardening',
    'hobby',
    'craft',
    'knitting',
    'crochet',
    'lego',
    'puzzle',
    'travel',
    'trip',
    'vacation',
    'holiday',
  ];

  static const List<String> _nightKeywords = [
    'sleep',
    'bed',
    'bedtime',
    'go to bed',
    'lights out',
    'wind down',
    'unwind',
    'night routine',
    'evening routine',
    'shutdown routine',
    'digital detox',
    'screen off',
    'no phone',
    'journal',
    'journaling',
    'gratitude',
    'reflection',
    'reflect',
    'plan tomorrow',
    'set clothes',
    'pack bag',
    'set alarm',
    'alarm',
    'meds',
    'night meds',
    'brush',
    'wash face',
    'face wash',
    'take shower',
    'pajamas',
    'pyjamas',
    'read before bed',
    'sleep prep',
    'power nap',
    'relax',
    'calm down',
    'stretch before bed',
    'prayer before bed',
    'meditation before bed',
    'white noise',
    'sleep music',
    'bed prep',
    'blanket',
  ];
}

class _KeywordRule {
  final String keyword;
  final TaskSuggestion suggestion;

  const _KeywordRule({
    required this.keyword,
    required this.suggestion,
  });
}
