import '../models/uworld_topic.dart';

final List<UWorldTopic> uworldSeed = [
  // GENERAL PRINCIPLES
  UWorldTopic(system: 'Biochemistry (General Principles)', subtopic: 'Amino acids, proteins, and enzymes', totalQuestions: 20),
  UWorldTopic(system: 'Biochemistry (General Principles)', subtopic: 'Bioenergetics and carbohydrate metabolism', totalQuestions: 21),
  UWorldTopic(system: 'Biochemistry (General Principles)', subtopic: 'Cell and molecular biology', totalQuestions: 17),
  UWorldTopic(system: 'Biochemistry (General Principles)', subtopic: 'Lipid metabolism', totalQuestions: 3),
  UWorldTopic(system: 'Biochemistry (General Principles)', subtopic: 'Miscellaneous', totalQuestions: 4),
  UWorldTopic(system: 'Genetics (General Principles)', subtopic: 'Clinical genetics', totalQuestions: 24),
  UWorldTopic(system: 'Genetics (General Principles)', subtopic: 'DNA structure, replication, and repair', totalQuestions: 18),
  UWorldTopic(system: 'Genetics (General Principles)', subtopic: 'Gene expression and regulation', totalQuestions: 8),
  UWorldTopic(system: 'Genetics (General Principles)', subtopic: 'Protein synthesis', totalQuestions: 1),
  UWorldTopic(system: 'Genetics (General Principles)', subtopic: 'RNA structure, synthesis, and processing', totalQuestions: 13),
  UWorldTopic(system: 'Genetics (General Principles)', subtopic: 'Miscellaneous', totalQuestions: 2),
  UWorldTopic(system: 'Microbiology (General Principles)', subtopic: 'Bacteriology', totalQuestions: 15),
  UWorldTopic(system: 'Microbiology (General Principles)', subtopic: 'Mycology', totalQuestions: 2),
  UWorldTopic(system: 'Microbiology (General Principles)', subtopic: 'Parasitology', totalQuestions: 1),
  UWorldTopic(system: 'Microbiology (General Principles)', subtopic: 'Virology', totalQuestions: 10),
  UWorldTopic(system: 'Microbiology (General Principles)', subtopic: 'Miscellaneous', totalQuestions: 2),
  UWorldTopic(system: 'Pathology (General Principles)', subtopic: 'Cellular pathology', totalQuestions: 6),
  UWorldTopic(system: 'Pathology (General Principles)', subtopic: 'Inflammation and repair', totalQuestions: 2),
  UWorldTopic(system: 'Pathology (General Principles)', subtopic: 'Neoplasia', totalQuestions: 31),
  UWorldTopic(system: 'Pharmacology (General Principles)', subtopic: 'Drug metabolism and toxicity', totalQuestions: 18),
  UWorldTopic(system: 'Pharmacology (General Principles)', subtopic: 'Drug receptors and pharmacodynamics', totalQuestions: 5),
  UWorldTopic(system: 'Pharmacology (General Principles)', subtopic: 'Pharmacokinetics', totalQuestions: 14),
  UWorldTopic(system: 'Pharmacology (General Principles)', subtopic: 'Miscellaneous', totalQuestions: 8),
  UWorldTopic(system: 'Biostatistics & Epidemiology', subtopic: 'Epidemiology and population health', totalQuestions: 31),
  UWorldTopic(system: 'Biostatistics & Epidemiology', subtopic: 'Measures and distribution of data', totalQuestions: 11),
  UWorldTopic(system: 'Biostatistics & Epidemiology', subtopic: 'Probability and principles of testing', totalQuestions: 23),
  UWorldTopic(system: 'Biostatistics & Epidemiology', subtopic: 'Study design and interpretation', totalQuestions: 54),
  UWorldTopic(system: 'Biostatistics & Epidemiology', subtopic: 'Miscellaneous', totalQuestions: 1),
  UWorldTopic(system: 'Poisoning & Environmental Exposure', subtopic: 'Environmental exposure', totalQuestions: 7),
  UWorldTopic(system: 'Poisoning & Environmental Exposure', subtopic: 'Toxicology', totalQuestions: 25),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Normal behavior and development', totalQuestions: 18),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Anxiety and trauma-related disorders', totalQuestions: 25),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Mood disorders', totalQuestions: 33),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Neurodevelopmental disorders', totalQuestions: 17),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Personality disorders', totalQuestions: 7),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Psychotic disorders', totalQuestions: 26),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Substance use disorders', totalQuestions: 26),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Eating disorders', totalQuestions: 8),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Somatoform disorders', totalQuestions: 2),
  UWorldTopic(system: 'Psychiatric/Behavioral & Substance Use Disorder', subtopic: 'Miscellaneous', totalQuestions: 18),
  UWorldTopic(system: 'Social Sciences (Ethics/Legal/Professional)', subtopic: 'Communication and interpersonal skills', totalQuestions: 62),
  UWorldTopic(system: 'Social Sciences (Ethics/Legal/Professional)', subtopic: 'Healthcare policy and economics', totalQuestions: 9),
  UWorldTopic(system: 'Social Sciences (Ethics/Legal/Professional)', subtopic: 'Medical ethics and jurisprudence', totalQuestions: 20),
  UWorldTopic(system: 'Social Sciences (Ethics/Legal/Professional)', subtopic: 'Patient safety', totalQuestions: 9),
  UWorldTopic(system: 'Social Sciences (Ethics/Legal/Professional)', subtopic: 'System based-practice and quality improvement', totalQuestions: 5),
  UWorldTopic(system: 'Social Sciences (Ethics/Legal/Professional)', subtopic: 'Miscellaneous', totalQuestions: 3),
  UWorldTopic(system: 'Miscellaneous (Multisystem)', subtopic: 'Miscellaneous', totalQuestions: 24),
  // ORGAN SYSTEMS
  UWorldTopic(system: 'Allergy & Immunology', subtopic: 'Anaphylaxis and allergic reactions', totalQuestions: 19),
  UWorldTopic(system: 'Allergy & Immunology', subtopic: 'Autoimmune diseases', totalQuestions: 13),
  UWorldTopic(system: 'Allergy & Immunology', subtopic: 'Immune deficiencies', totalQuestions: 23),
  UWorldTopic(system: 'Allergy & Immunology', subtopic: 'Transplant medicine', totalQuestions: 7),
  UWorldTopic(system: 'Allergy & Immunology', subtopic: 'Principles of immunology', totalQuestions: 25),
  UWorldTopic(system: 'Allergy & Immunology', subtopic: 'Miscellaneous', totalQuestions: 21),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Normal structure and function', totalQuestions: 55),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Aortic and peripheral artery diseases', totalQuestions: 37),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Cardiac arrhythmias', totalQuestions: 50),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Congenital heart disease', totalQuestions: 32),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Coronary heart disease', totalQuestions: 47),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Heart failure and shock', totalQuestions: 46),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Hypertension', totalQuestions: 24),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Myopericardial diseases', totalQuestions: 52),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Valvular heart diseases', totalQuestions: 46),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Cardiovascular drugs', totalQuestions: 17),
  UWorldTopic(system: 'Cardiovascular System', subtopic: 'Miscellaneous', totalQuestions: 11),
  UWorldTopic(system: 'Dermatology', subtopic: 'Normal structure and function of skin', totalQuestions: 6),
  UWorldTopic(system: 'Dermatology', subtopic: 'Disorders of epidermal appendages', totalQuestions: 11),
  UWorldTopic(system: 'Dermatology', subtopic: 'Inflammatory dermatoses and bullous diseases', totalQuestions: 28),
  UWorldTopic(system: 'Dermatology', subtopic: 'Skin and soft tissue infections', totalQuestions: 18),
  UWorldTopic(system: 'Dermatology', subtopic: 'Skin tumors and tumor-like lesions', totalQuestions: 32),
  UWorldTopic(system: 'Dermatology', subtopic: 'Miscellaneous', totalQuestions: 5),
  UWorldTopic(system: 'Ear, Nose & Throat (ENT)', subtopic: 'Disorders of the ear, nose, and throat', totalQuestions: 40),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Normal structure and function of endocrine glands', totalQuestions: 3),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Congenital and developmental anomalies', totalQuestions: 19),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Adrenal disorders', totalQuestions: 11),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Diabetes mellitus', totalQuestions: 49),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Endocrine tumors', totalQuestions: 26),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Hypothalamus and pituitary disorders', totalQuestions: 13),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Obesity and dyslipidemia', totalQuestions: 13),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Reproductive endocrinology', totalQuestions: 21),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Thyroid disorders', totalQuestions: 34),
  UWorldTopic(system: 'Endocrine, Diabetes & Metabolism', subtopic: 'Miscellaneous', totalQuestions: 10),
  UWorldTopic(system: 'Female Reproductive System & Breast', subtopic: 'Normal structure and function', totalQuestions: 11),
  UWorldTopic(system: 'Female Reproductive System & Breast', subtopic: 'Congenital and developmental anomalies', totalQuestions: 10),
  UWorldTopic(system: 'Female Reproductive System & Breast', subtopic: 'Breast disorders', totalQuestions: 7),
  UWorldTopic(system: 'Female Reproductive System & Breast', subtopic: 'Genital tract tumors and tumor-like lesions', totalQuestions: 26),
  UWorldTopic(system: 'Female Reproductive System & Breast', subtopic: 'Genitourinary tract infections', totalQuestions: 13),
  UWorldTopic(system: 'Female Reproductive System & Breast', subtopic: 'Menstrual disorders and contraception', totalQuestions: 4),
  UWorldTopic(system: 'Female Reproductive System & Breast', subtopic: 'Miscellaneous', totalQuestions: 8),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Normal structure and function of the GI tract', totalQuestions: 22),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Congenital and developmental anomalies', totalQuestions: 21),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Biliary tract disorders', totalQuestions: 17),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Disorders of nutrition', totalQuestions: 18),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Gastroesophageal disorders', totalQuestions: 45),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Hepatic disorders', totalQuestions: 60),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Intestinal and colorectal disorders', totalQuestions: 66),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Pancreatic disorders', totalQuestions: 17),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Tumors of the GI tract', totalQuestions: 27),
  UWorldTopic(system: 'Gastrointestinal & Nutrition', subtopic: 'Miscellaneous', totalQuestions: 14),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'Normal hematologic structure and function', totalQuestions: 10),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'Hemostasis and thrombosis', totalQuestions: 37),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'Plasma cell disorders', totalQuestions: 2),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'Platelet disorders', totalQuestions: 15),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'Red blood cell disorders', totalQuestions: 85),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'Transfusion medicine', totalQuestions: 4),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'White blood cell disorders', totalQuestions: 48),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'Principles of oncology', totalQuestions: 22),
  UWorldTopic(system: 'Hematology & Oncology', subtopic: 'Miscellaneous', totalQuestions: 7),
  UWorldTopic(system: 'Infectious Diseases', subtopic: 'Antimicrobial drugs', totalQuestions: 23),
  UWorldTopic(system: 'Infectious Diseases', subtopic: 'Bacterial infections', totalQuestions: 112),
  UWorldTopic(system: 'Infectious Diseases', subtopic: 'Fungal infections', totalQuestions: 12),
  UWorldTopic(system: 'Infectious Diseases', subtopic: 'HIV and sexually transmitted infections', totalQuestions: 42),
  UWorldTopic(system: 'Infectious Diseases', subtopic: 'Infection control', totalQuestions: 6),
  UWorldTopic(system: 'Infectious Diseases', subtopic: 'Parasitic and helminthic infections', totalQuestions: 26),
  UWorldTopic(system: 'Infectious Diseases', subtopic: 'Viral infections', totalQuestions: 44),
  UWorldTopic(system: 'Infectious Diseases', subtopic: 'Miscellaneous', totalQuestions: 7),
  UWorldTopic(system: 'Male Reproductive System', subtopic: 'Normal structure and function', totalQuestions: 4),
  UWorldTopic(system: 'Male Reproductive System', subtopic: 'Disorders of the male reproductive system', totalQuestions: 48),
  UWorldTopic(system: 'Nervous System', subtopic: 'Normal structure and function', totalQuestions: 48),
  UWorldTopic(system: 'Nervous System', subtopic: 'Congenital and developmental anomalies', totalQuestions: 36),
  UWorldTopic(system: 'Nervous System', subtopic: 'Cerebrovascular disease', totalQuestions: 62),
  UWorldTopic(system: 'Nervous System', subtopic: 'CNS infections', totalQuestions: 30),
  UWorldTopic(system: 'Nervous System', subtopic: 'Demyelinating diseases', totalQuestions: 9),
  UWorldTopic(system: 'Nervous System', subtopic: 'Disorders of peripheral nerves and muscles', totalQuestions: 69),
  UWorldTopic(system: 'Nervous System', subtopic: 'Headache', totalQuestions: 12),
  UWorldTopic(system: 'Nervous System', subtopic: 'Neurodegenerative disorders and dementias', totalQuestions: 34),
  UWorldTopic(system: 'Nervous System', subtopic: 'Seizures and epilepsy', totalQuestions: 19),
  UWorldTopic(system: 'Nervous System', subtopic: 'Spinal cord disorders', totalQuestions: 14),
  UWorldTopic(system: 'Nervous System', subtopic: 'Traumatic brain injuries', totalQuestions: 8),
  UWorldTopic(system: 'Nervous System', subtopic: 'Tumors of the nervous system', totalQuestions: 17),
  UWorldTopic(system: 'Nervous System', subtopic: 'Hydrocephalus', totalQuestions: 5),
  UWorldTopic(system: 'Nervous System', subtopic: 'Anesthesia', totalQuestions: 12),
  UWorldTopic(system: 'Nervous System', subtopic: 'Sleep disorders', totalQuestions: 8),
  UWorldTopic(system: 'Nervous System', subtopic: 'Miscellaneous', totalQuestions: 18),
  UWorldTopic(system: 'Ophthalmology', subtopic: 'Normal structure and function of the eye', totalQuestions: 3),
  UWorldTopic(system: 'Ophthalmology', subtopic: 'Disorders of the eye and associated structures', totalQuestions: 28),
  UWorldTopic(system: 'Pregnancy, Childbirth & Puerperium', subtopic: 'Normal pregnancy, childbirth, and puerperium', totalQuestions: 15),
  UWorldTopic(system: 'Pregnancy, Childbirth & Puerperium', subtopic: 'Disorders of pregnancy, childbirth, and puerperium', totalQuestions: 44),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Normal pulmonary structure and function', totalQuestions: 25),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Congenital and developmental anomalies', totalQuestions: 9),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Critical care medicine', totalQuestions: 40),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Interstitial lung disease', totalQuestions: 26),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Lung cancer', totalQuestions: 10),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Obstructive lung disease', totalQuestions: 48),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Pulmonary infections', totalQuestions: 61),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Pulmonary vascular disease', totalQuestions: 23),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Sleep disorders', totalQuestions: 1),
  UWorldTopic(system: 'Pulmonary & Critical Care', subtopic: 'Miscellaneous', totalQuestions: 21),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Normal structure and function', totalQuestions: 24),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Congenital and developmental anomalies', totalQuestions: 21),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Acute kidney injury', totalQuestions: 22),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Bone metabolism', totalQuestions: 8),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Chronic kidney disease', totalQuestions: 14),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Cystic kidney diseases', totalQuestions: 3),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Fluid, electrolytes, and acid-base', totalQuestions: 38),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Glomerular diseases', totalQuestions: 39),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Neoplasms of the kidneys and urinary tract', totalQuestions: 12),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Nephrolithiasis and urinary tract obstruction', totalQuestions: 16),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Diabetes insipidus', totalQuestions: 8),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Urinary incontinence', totalQuestions: 5),
  UWorldTopic(system: 'Renal, Urinary Systems & Electrolytes', subtopic: 'Miscellaneous', totalQuestions: 15),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Normal structure and function of the musculoskeletal system', totalQuestions: 31),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Congenital and developmental anomalies', totalQuestions: 9),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Arthritis and spondyloarthropathies', totalQuestions: 38),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Autoimmune disorders and vasculitides', totalQuestions: 25),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Bone/joint injuries and infections', totalQuestions: 35),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Bone tumors and tumor-like lesions', totalQuestions: 6),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Spinal disorders and back pain', totalQuestions: 4),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Metabolic bone disorders', totalQuestions: 14),
  UWorldTopic(system: 'Rheumatology/Orthopedics & Sports', subtopic: 'Miscellaneous', totalQuestions: 6),
];
